name: Fly Deploy

on:
  push:
    branches:
      - main
    paths:
      - "voro-salon-crm-api/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Fly.io Secrets
        run: |
          cd ${{ secrets.FOLDER__API }}
          flyctl secrets set \
            JWTKEY="${{ secrets.JWTKEY }}" \
            BIRTHDAY_API_KEY="${{ secrets.BIRTHDAY_API_KEY }}" \
            CONNECTIONSTRING__PRODUCTION__SERVER="${{ secrets.CONNECTIONSTRING__PRODUCTION__SERVER }}" \
            CONNECTIONSTRING__PRODUCTION__PORT="${{ secrets.CONNECTIONSTRING__PRODUCTION__PORT }}" \
            CONNECTIONSTRING__PRODUCTION__DATABASE="${{ secrets.CONNECTIONSTRING__PRODUCTION__DATABASE }}" \
            CONNECTIONSTRING__PRODUCTION__USERID="${{ secrets.CONNECTIONSTRING__PRODUCTION__USERID }}" \
            CONNECTIONSTRING__PRODUCTION__PASSWORD="${{ secrets.CONNECTIONSTRING__PRODUCTION__PASSWORD }}" \
            EMAILSETTINGS__SMTPSERVER="${{ secrets.EMAILSETTINGS__SMTPSERVER }}" \
            EMAILSETTINGS__SMTPPORT="${{ secrets.EMAILSETTINGS__SMTPPORT }}" \
            EMAILSETTINGS__IMAPSERVER="${{ secrets.EMAILSETTINGS__IMAPSERVER }}" \
            EMAILSETTINGS__IMAPPORT="${{ secrets.EMAILSETTINGS__IMAPPORT }}" \
            EMAILSETTINGS__FROM="${{ secrets.EMAILSETTINGS__FROM }}" \
            EMAILSETTINGS__USERNAME="${{ secrets.EMAILSETTINGS__USERNAME }}" \
            EMAILSETTINGS__PASSWORD="${{ secrets.EMAILSETTINGS__PASSWORD }}" \
            BLOBSETTINGS__TOKEN="${{ secrets.BLOBSETTINGS__TOKEN }}" \
            BLOBSETTINGS__STOREID="${{ secrets.BLOBSETTINGS__STOREID }}" \
            BLOBSETTINGS__BLOBNAME="${{ secrets.BLOBSETTINGS__BLOBNAME }}" \
            MERCADOPAGOSETTINGS__BACKURL="${{ secrets.MERCADOPAGOSETTINGS__BACKURL }}" \
            MERCADOPAGOSETTINGS__ACCESSTOKEN="${{ secrets.MERCADOPAGOSETTINGS__ACCESSTOKEN }}" \
            MERCADOPAGOSETTINGS__WEBHOOKSECRET="${{ secrets.MERCADOPAGOSETTINGS__WEBHOOKSECRET }}" \
            KESTREL__CERTIFICATES__DEVELOPMENT__PASSWORD="${{ secrets.KESTREL__CERTIFICATES__DEVELOPMENT__PASSWORD }}" \
            AISETTINGS__APIKEY="${{ secrets.AISETTINGS__APIKEY }} " \
            OPENAISETTINGS__APIKEY=${{ secrets.OPENAISETTINGS__APIKEY }} \
            INTEGRATIONSETTINGS__WHATSAPP__APPID="${{ secrets.INTEGRATIONSETTINGS__WHATSAPP__APPID }} " \
            INTEGRATIONSETTINGS__WHATSAPP__CONFIGID="${{ secrets.INTEGRATIONSETTINGS__WHATSAPP__CONFIGID }} " \
            INTEGRATIONSETTINGS__WHATSAPP__APPSECRET="${{ secrets.INTEGRATIONSETTINGS__WHATSAPP__APPSECRET }} " \
            INTEGRATIONSETTINGS__WHATSAPP__MASTERACCESSTOKEN="${{ secrets.INTEGRATIONSETTINGS__WHATSAPP__MASTERACCESSTOKEN }} " \
            INTEGRATIONSETTINGS__WHATSAPP__TOKEN="${{ secrets.INTEGRATIONSETTINGS__WHATSAPP__TOKEN }}" \
            INTEGRATIONSETTINGS__WHATSAPP__PHONEID="${{ secrets.INTEGRATIONSETTINGS__WHATSAPP__PHONEID }}" \
            INTEGRATIONSETTINGS__WHATSAPP__BUSSINESSID="${{ secrets.INTEGRATIONSETTINGS__WHATSAPP__BUSSINESSID }}" \
            INTEGRATIONSETTINGS__WHATSAPP__VERIFYTOKEN="${{ secrets.INTEGRATIONSETTINGS__WHATSAPP__VERIFYTOKEN }}" \
            CORSSETTINGS__ALLOWEDORIGINS__0="${{ secrets.CORSSETTINGS__ALLOWEDORIGINS__0 }}" \
            CORSSETTINGS__ALLOWEDORIGINS__1="${{ secrets.CORSSETTINGS__ALLOWEDORIGINS__1 }}" \
            CORSSETTINGS__ALLOWEDORIGINS__2="${{ secrets.CORSSETTINGS__ALLOWEDORIGINS__2 }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: |
          cd ${{ secrets.FOLDER__API }}
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
