name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # importante para mirror

      - name: Push to personal repo
        run: |
          git remote add mirror https://x-access-token:${{ secrets.PERSONAL_REPO_TOKEN }}@github.com/vorolabs-app/${{ github.event.repository.name }}-deploy.git
          git push --mirror mirror